name: CI/CD Pipeline
run-name: Running CI/CD Pipeline

on: [push, pull_request]

jobs:
  Run-Tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run tests & coverage
        run: pytest
